version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: filevault
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/filevault?sslmode=disable
      STORAGE_DIR: /data
      RATE_LIMIT_RPS: 2
      USER_QUOTA_BYTES: 10485760
    volumes:
      - storage_data:/data
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080/graphql
    depends_on:
      - backend

volumes:
  db_data: {}
  storage_data: {}


